### ISSUE TITLE
MailChimp API integration

### ISSUE THREAD

**Issue by matiaskorhonen** [kiskolabs/splendidbacon#11]
Remove/add people from the mailing list when they create/delete their accounts.

Maybe add a "Subscribe to Newsletter" type option to user profiles?

**Comment by akonan** [comment]
Yes. Fetch the current status from MailChimp if they exist there.

**Comment by matiaskorhonen** [comment]
Adds Mailchimp newsletter subscription integration. Closed by f25c815130c2cd621b89c8be1e81b5ffacd554de
