### ISSUE TITLE
Rethink the built by line on the homepage

### ISSUE THREAD

**Issue by matiaskorhonen** [kiskolabs/splendidbacon#23]
<div class="thumbnail"><a href="https://skitch.com/k33l0r/r84ji/splendid-bacon-built-by"><img style="max-width:638px" src="https://img.skitch.com/20110105-gp77d3haa3yaekcwamc7tyikbd.medium.jpg" alt="Splendid Bacon - Built By" /></a><br /><span>Uploaded with <a href="http://skitch.com">Skitch</a>!</span></div>

Maybe it should be built by Kisko Labs, and maybe we should link to the Kisko blog/twitter account and/or SB twitter account?

**Comment by jcxplorer** [comment]
We can make the Blog link point to http://blog.kiskolabs.com/tagged/splendidbacon .

**Comment by matiaskorhonen** [comment]
Done in next
