### ISSUE TITLE
Small problem in project show

### ISSUE THREAD

**Issue by akonan** [kiskolabs/splendidbacon#25]
...
see video with voice over

http://screencast.com/t/uph6XwwD

May be a bug, expected behaviour or whatever
but didnt respond as I would have expeted

Alec

**Comment by matiaskorhonen** [comment]
I agree. The countdown should show something else if the project is on hold or completed...

**Comment by matiaskorhonen** [comment]
Fixed in the 'next' branch: d115eee5de25422119aab4ec89dd5d3eca2854f0
