### ISSUE TITLE
Organization dropdown has a bug 

### ISSUE THREAD

**Issue by akonan** [kiskolabs/splendidbacon#32]
"When I add another organization, the name appears as duplicate of another existing one on the top left corner.
The bug only appears when i'm inside the new organization."

https://skitch.com/akonan/r6s1s/fa8i9kuh9jyx7fm-1280x800

**Comment by matiaskorhonen** [comment]
Cannot replicate in development. There are two users2cash organisations in the production DB, most likely cause of the user's troubles...
