### ISSUE TITLE
Small ui tweak

### ISSUE THREAD

**Issue by akonan** [kiskolabs/splendidbacon#33]
"I noticed a positioning bug and as graphic designer I made a mockup if you want to consider :)"

https://skitch.com/akonan/r6s16/https-splendidbacon.zendesk.com-attachments-token-ltyvidrfcfsitpf-name-position-tweak.jpg

https://skitch.com/akonan/r6sun/https-splendidbacon.zendesk.com-attachments-token-5seks7lwtyie621-name-redesign-proposal.png

**Comment by antsa** [comment]
Too bad Matias didn't consider the bacon proposal..

**Comment by matiaskorhonen** [comment]
You can change it if you like.
